import { useEditor } from './src/store/editorStore';
const store = useEditor.getState();
console.log('initial length', store.elements.length);
store.addPhoto('data:image/png;base64,AAA', 100, 100);
let s = useEditor.getState();
console.log('after add length', s.elements.length);
const id = s.elements[0].id;
store.removeElement(id);
s = useEditor.getState();
console.log('after remove length', s.elements.length);
